Add phone number as an optional requirement
hackclub-archive/website pull request #290
Opened 2017-02-07 02:51 UTC by paked

This PR adds a new field to the ClubApplication model. It enables us to collect the phone numbers of our new applicatants who are more comfortable with a non-email form of communication.

Things to do:
- [ ] Write some sort of copy which explains what we'll do with the phone number.
  - I'm not sure what this will look like, so going to talk to @kyleemile about it tomorrow.

2017-02-07 04:38 UTC, zachlatta commented
Tests!

Sent from my mobile

> On Feb 6, 2017, at 18:51, Harrison Shoebridge <notifications@github.com> wrote:
> 
> This PR adds a new field to the ClubApplication model. It enables us to collect the phone numbers of our new applicatants who are more comfortable with a non-email form of communication.
> 
> Things to do:
> 
>  Write some sort of copy which explains what we'll do with the phone number.
> I'm not sure what this will look like, so going to talk to @kyleemile about it tomorrow.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/hackclub/website/pull/290
> 
> Commit Summary
> 
> Add phone number as an optional requirement
> File Changes
> 
> M app/controllers/club_applications_controller.rb (5)
> M app/views/club_applications/_club_application.text.erb (1)
> M app/views/club_applications/new.html.haml (4)
> A db/migrate/20170207021033_add_phone_number_to_club_application.rb (5)
> M db/schema.rb (3)
> Patch Links:
> 
> https://github.com/hackclub/website/pull/290.patch
> https://github.com/hackclub/website/pull/290.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-02-07 04:38 UTC, zachlatta commented
Add tests!

Sent from my mobile

> On Feb 6, 2017, at 18:51, Harrison Shoebridge <notifications@github.com> wrote:
> 
> This PR adds a new field to the ClubApplication model. It enables us to collect the phone numbers of our new applicatants who are more comfortable with a non-email form of communication.
> 
> Things to do:
> 
>  Write some sort of copy which explains what we'll do with the phone number.
> I'm not sure what this will look like, so going to talk to @kyleemile about it tomorrow.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/hackclub/website/pull/290
> 
> Commit Summary
> 
> Add phone number as an optional requirement
> File Changes
> 
> M app/controllers/club_applications_controller.rb (5)
> M app/views/club_applications/_club_application.text.erb (1)
> M app/views/club_applications/new.html.haml (4)
> A db/migrate/20170207021033_add_phone_number_to_club_application.rb (5)
> M db/schema.rb (3)
> Patch Links:
> 
> https://github.com/hackclub/website/pull/290.patch
> https://github.com/hackclub/website/pull/290.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-02-07 13:31 UTC, paked commented
@zachlatta: Tests that do what? Phone numbers are empty, so there's no need to test for presence.

2017-02-07 16:11 UTC, zachlatta requested changes
- Test for new `phone_number` field needs to be added to https://github.com/hackclub/website/blob/83d288b5f7b4e738ef49afe11e32720573b6bfc0/spec/models/club_application_spec.rb#L9-L19
- You should add the `phone_number` field to the `ClubApplication` factory (in `spec/factories/club_application.rb`).
- Do you want to do any sort of validation of the phone number?

2017-02-07 16:11 UTC, zachlatta commented on app/views/club_applications/_club_application.text.erb
> +Phone Number: <%= if club_application.phone_number.blank? then 'N/A' else club_application.phone_number end %>
No need for the "N/A" if it's blank. GitHub or Twitter can be blank and we don't set them to "N/A" if they're not set.

2017-02-07 16:11 UTC, zachlatta commented on app/views/club_applications/new.html.haml
> +          = f.input :phone_number, label: "Phone number (we'll get in touch to answer any questions you might have)",placeholder: '(555) 555-5555'
`you might have)",placeholder: '(555) 555-5555'`

should be

`you might have)", placeholder: '(555) 555-5555'` (extra space after comma)

2017-02-07 21:27 UTC, MaxWofford commented
@paked: LGTM. Not merging because @zachlatta is assigned.

2017-02-08 00:22 UTC, zachlatta commented
LGTM. One final change needed, sorry for not catching that earlier.

2017-02-08 00:22 UTC, zachlatta requested changes

2017-02-08 00:22 UTC, zachlatta commented on db/migrate/20170207021033_add_phone_number_to_club_application.rb
> +    add_column :club_applications, :phone_number, :string
This should be `text`. You should never use the `string` type in Postgres because it's limited to 255 chars.

2017-02-08 00:56 UTC, paked commented on db/migrate/20170207021033_add_phone_number_to_club_application.rb
> +    add_column :club_applications, :phone_number, :string
@zachlatta: `string` is used for all of the other non long form data types in the database. I did it to be consistent.

2017-02-08 00:56 UTC, paked commented
@zachlatta: Hey! Ready to merge.

2017-02-08 01:00 UTC, zachlatta commented on db/migrate/20170207021033_add_phone_number_to_club_application.rb
> +    add_column :club_applications, :phone_number, :string
Ah, thanks for catching that. My bad!

2017-02-08 01:00 UTC, zachlatta approved these changes

2017-02-08 01:00 UTC, merged